import {Card} from './classesJS.js';

let deck = [];
deck.push(new Card('cross', '2', 2, 0));
deck.push(new Card('cross', '3', 3, 1));
deck.push(new Card('cross', '4', 4, 2));
deck.push(new Card('cross', '5', 5, 3));
deck.push(new Card('cross', '6', 6, 4));
deck.push(new Card('cross', '7', 7, 5));
deck.push(new Card('cross', '8', 8, 6));
deck.push(new Card('cross', '9', 9, 7));
deck.push(new Card('cross', '10', 10, 8));
deck.push(new Card('cross', 'jack', 11, 9));
deck.push(new Card('cross', 'queen', 12, 10));
deck.push(new Card('cross', 'king', 13, 11));
deck.push(new Card('cross', 'ace', 14, 12));

deck.push(new Card('diamonds', '2', 2, 13));
deck.push(new Card('diamonds', '3', 3, 14));
deck.push(new Card('diamonds', '4', 4, 15));
deck.push(new Card('diamonds', '5', 5, 16));
deck.push(new Card('diamonds', '6', 6, 17));
deck.push(new Card('diamonds', '7', 7, 18));
deck.push(new Card('diamonds', '8', 8, 19));
deck.push(new Card('diamonds', '9', 9, 20));
deck.push(new Card('diamonds', '10', 10, 21));
deck.push(new Card('diamonds', 'jack', 11, 22));
deck.push(new Card('diamonds', 'queen', 12, 23));
deck.push(new Card('diamonds', 'king', 13, 24));
deck.push(new Card('diamonds', 'ace', 14, 25));

deck.push(new Card('peaks', '2', 2, 26));
deck.push(new Card('peaks', '3', 3, 27));
deck.push(new Card('peaks', '4', 4, 28));
deck.push(new Card('peaks', '5', 5, 29));
deck.push(new Card('peaks', '6', 6, 30));
deck.push(new Card('peaks', '7', 7, 31));
deck.push(new Card('peaks', '8', 8, 32));
deck.push(new Card('peaks', '9', 9, 33));
deck.push(new Card('peaks', '10', 10, 34));
deck.push(new Card('peaks', 'jack', 11, 35));
deck.push(new Card('peaks', 'queen', 12, 36));
deck.push(new Card('peaks', 'king', 13, 37));
deck.push(new Card('peaks', 'ace', 14, 38));

deck.push(new Card('hearts', '2', 2, 39));
deck.push(new Card('hearts', '3', 3, 40));
deck.push(new Card('hearts', '4', 4, 41));
deck.push(new Card('hearts', '5', 5, 42));
deck.push(new Card('hearts', '6', 6, 43));
deck.push(new Card('hearts', '7', 7, 44));
deck.push(new Card('hearts', '8', 8, 45));
deck.push(new Card('hearts', '9', 9, 46));
deck.push(new Card('hearts', '10', 10, 47));
deck.push(new Card('hearts', 'jack', 11, 48));
deck.push(new Card('hearts', 'queen', 12, 49));
deck.push(new Card('hearts', 'king', 13, 50));
deck.push(new Card('hearts', 'ace', 14, 51));

export {deck};